/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lojaesportiva;

import javax.swing.JOptionPane;

/**
 *
 * @author Ingrid
 */
public class TeladeVendas extends javax.swing.JFrame {

    /**
     * Creates new form TeladeVendas
     */
    public TeladeVendas() {
        initComponents(); 
        
        setLocationRelativeTo (null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marcasgrupo1 = new javax.swing.ButtonGroup();
        Tamanhogrupo2 = new javax.swing.ButtonGroup();
        Produtosgrupo3 = new javax.swing.ButtonGroup();
        Servicosgrupo4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tglAdidas = new javax.swing.JToggleButton();
        tglPuma = new javax.swing.JToggleButton();
        tglNike = new javax.swing.JToggleButton();
        tglGYM = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        rboPP = new javax.swing.JRadioButton();
        rboM = new javax.swing.JRadioButton();
        rboGG = new javax.swing.JRadioButton();
        rbo35 = new javax.swing.JRadioButton();
        rbo40 = new javax.swing.JRadioButton();
        rbo1 = new javax.swing.JRadioButton();
        rbo6 = new javax.swing.JRadioButton();
        rbo13 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rboTenis = new javax.swing.JRadioButton();
        rboCamisetas = new javax.swing.JRadioButton();
        rboCalcas = new javax.swing.JRadioButton();
        rboShorts = new javax.swing.JRadioButton();
        rboSutias = new javax.swing.JRadioButton();
        rboPesos = new javax.swing.JRadioButton();
        rboBones = new javax.swing.JRadioButton();
        rboLuvas = new javax.swing.JRadioButton();
        rboMeias = new javax.swing.JRadioButton();
        rboSungas = new javax.swing.JRadioButton();
        rboBolas = new javax.swing.JRadioButton();
        rboRaquetes = new javax.swing.JRadioButton();
        rboPranchas = new javax.swing.JRadioButton();
        rboCabacetes = new javax.swing.JRadioButton();
        rboBolsas = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        chkGarantia = new javax.swing.JCheckBox();
        chkDesconto = new javax.swing.JCheckBox();
        chkParcelamentos = new javax.swing.JCheckBox();
        cboTipoParce = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Artigos Esportivos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 24))); // NOI18N

        Marcasgrupo1.add(tglAdidas);
        tglAdidas.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tglAdidas.setText("Adidas");
        tglAdidas.setActionCommand("Adidas");

        Marcasgrupo1.add(tglPuma);
        tglPuma.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tglPuma.setText("Puma");
        tglPuma.setActionCommand("Puma");

        Marcasgrupo1.add(tglNike);
        tglNike.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tglNike.setText("Nike");
        tglNike.setActionCommand("Nike");

        Marcasgrupo1.add(tglGYM);
        tglGYM.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tglGYM.setText("GYM");
        tglGYM.setActionCommand("GYM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglNike, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tglGYM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglGYM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tglNike, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tglAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tglPuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha um Tamanho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 24))); // NOI18N

        Tamanhogrupo2.add(rboPP);
        rboPP.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboPP.setText("PP/P");
        rboPP.setActionCommand("PP/P");

        Tamanhogrupo2.add(rboM);
        rboM.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboM.setText("M");
        rboM.setActionCommand("M");
        rboM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboMActionPerformed(evt);
            }
        });

        Tamanhogrupo2.add(rboGG);
        rboGG.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboGG.setText("G/GG");
        rboGG.setActionCommand("G/GG");

        Tamanhogrupo2.add(rbo35);
        rbo35.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbo35.setText("35 ao 37");
        rbo35.setActionCommand("35 ao 37");

        Tamanhogrupo2.add(rbo40);
        rbo40.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbo40.setText("38 ao 44");
        rbo40.setActionCommand("38 ao 44");

        Tamanhogrupo2.add(rbo1);
        rbo1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbo1.setText("1 á 5 kg");

        Tamanhogrupo2.add(rbo6);
        rbo6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbo6.setText("6 á 12 Kg");

        Tamanhogrupo2.add(rbo13);
        rbo13.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rbo13.setText("13 á 30 Kg");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rboPP)
                    .addComponent(rboM)
                    .addComponent(rboGG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbo40)
                    .addComponent(rbo35))
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbo1)
                    .addComponent(rbo6)
                    .addComponent(rbo13))
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboPP)
                    .addComponent(rbo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rboM)
                    .addComponent(rbo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbo13)
                    .addComponent(rboGG))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbo35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbo40)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 24))); // NOI18N

        Produtosgrupo3.add(rboTenis);
        rboTenis.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboTenis.setText("Tênis");
        rboTenis.setActionCommand("Tenis");

        Produtosgrupo3.add(rboCamisetas);
        rboCamisetas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboCamisetas.setText("Camisetas");
        rboCamisetas.setActionCommand("Camisetas");

        Produtosgrupo3.add(rboCalcas);
        rboCalcas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboCalcas.setText("Calças");
        rboCalcas.setActionCommand("Calcas");

        Produtosgrupo3.add(rboShorts);
        rboShorts.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboShorts.setText("Shorts");
        rboShorts.setActionCommand("Shorts");

        Produtosgrupo3.add(rboSutias);
        rboSutias.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboSutias.setText("Sutiãs Esportivos");
        rboSutias.setActionCommand("Sutias Esportivos");

        Produtosgrupo3.add(rboPesos);
        rboPesos.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboPesos.setText("Pesos");
        rboPesos.setActionCommand("Pesos");

        Produtosgrupo3.add(rboBones);
        rboBones.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboBones.setText("Bonés");
        rboBones.setActionCommand("Bones");

        Produtosgrupo3.add(rboLuvas);
        rboLuvas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboLuvas.setText("Luvas");
        rboLuvas.setActionCommand("Luvas");

        Produtosgrupo3.add(rboMeias);
        rboMeias.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboMeias.setText("Meias");
        rboMeias.setActionCommand("Meias");

        Produtosgrupo3.add(rboSungas);
        rboSungas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboSungas.setText("Sungas");
        rboSungas.setActionCommand("Sungas");

        Produtosgrupo3.add(rboBolas);
        rboBolas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboBolas.setText("Bolas");
        rboBolas.setActionCommand("Bolsas");

        Produtosgrupo3.add(rboRaquetes);
        rboRaquetes.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboRaquetes.setText("Raquetes");
        rboRaquetes.setActionCommand("Raquetes");

        Produtosgrupo3.add(rboPranchas);
        rboPranchas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboPranchas.setText("Pranchas");
        rboPranchas.setActionCommand("Pranchas");

        Produtosgrupo3.add(rboCabacetes);
        rboCabacetes.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboCabacetes.setText("Cabacetes");
        rboCabacetes.setActionCommand("Capacetes");

        Produtosgrupo3.add(rboBolsas);
        rboBolsas.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        rboBolsas.setText("Bolsas");
        rboBolsas.setActionCommand("Bolsas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rboTenis)
                    .addComponent(rboCamisetas)
                    .addComponent(rboCalcas)
                    .addComponent(rboShorts)
                    .addComponent(rboSutias))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rboPesos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rboBolas)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rboMeias)
                                    .addComponent(rboSungas))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rboCabacetes)
                                    .addComponent(rboBolsas)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rboBones)
                                    .addComponent(rboLuvas))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rboPranchas)
                                    .addComponent(rboRaquetes))))
                        .addGap(53, 53, 53))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboPesos)
                            .addComponent(rboBolas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboBones)
                            .addComponent(rboRaquetes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboLuvas)
                            .addComponent(rboPranchas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboMeias)
                            .addComponent(rboCabacetes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rboSungas)
                            .addComponent(rboBolsas)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rboTenis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rboCamisetas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rboCalcas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rboShorts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rboSutias)))
                .addGap(15, 15, 15))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serviços", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 1, 24))); // NOI18N

        Servicosgrupo4.add(chkGarantia);
        chkGarantia.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        chkGarantia.setText("Garantia Estendida");
        chkGarantia.setActionCommand("Garantia Estendida");

        Servicosgrupo4.add(chkDesconto);
        chkDesconto.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        chkDesconto.setText("Cupom de Desconto");
        chkDesconto.setActionCommand("Cupom de Desconto");

        Servicosgrupo4.add(chkParcelamentos);
        chkParcelamentos.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        chkParcelamentos.setText("Parcelamentos");
        chkParcelamentos.setActionCommand("Parcelamentos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkGarantia)
                    .addComponent(chkDesconto)
                    .addComponent(chkParcelamentos))
                .addGap(0, 309, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(chkGarantia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDesconto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkParcelamentos))
        );

        cboTipoParce.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        cboTipoParce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Parcelamento...", "Á vista ", "Dividido em 2x", "Dividido em 3x", "Dividido em 4x", "Dividido em 5x", "Dividido em 6x", "Dividido em 7x", "Dividido em 8x", "Dividido em 9x", "Dividido em 10x" }));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close-icon.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnSalvar});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cboTipoParce, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoParce, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String Marcas = Marcasgrupo1.getSelection().getActionCommand();
        
        String Tamanho = Tamanhogrupo2.getSelection().getActionCommand();
        
        String Produto = Produtosgrupo3.getSelection().getActionCommand();
        
        String Servicos = "";
        if(chkGarantia.isSelected()){
            Servicos += chkGarantia.getText() + " ";
        }
        if(chkDesconto.isSelected()){
            Servicos += chkDesconto.getText() + " ";
        }
        if(chkParcelamentos.isSelected()){
            Servicos += chkParcelamentos.getText() + " ";
        }
        
        String Parcelamentos = cboTipoParce.getSelectedItem().toString();

        
        JOptionPane.showMessageDialog(this, "Você Selecionou a marca: " + Marcas + "\n" +
                "Tamanho: " + Tamanho + "\n" +
                "Produto: " + Produto + "\n" +
                "Servicos: " + Servicos + "\n" +
                "Parcelamento: " + Parcelamentos 
        );
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void rboMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rboMActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeladeVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Marcasgrupo1;
    private javax.swing.ButtonGroup Produtosgrupo3;
    private javax.swing.ButtonGroup Servicosgrupo4;
    private javax.swing.ButtonGroup Tamanhogrupo2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboTipoParce;
    private javax.swing.JCheckBox chkDesconto;
    private javax.swing.JCheckBox chkGarantia;
    private javax.swing.JCheckBox chkParcelamentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbo1;
    private javax.swing.JRadioButton rbo13;
    private javax.swing.JRadioButton rbo35;
    private javax.swing.JRadioButton rbo40;
    private javax.swing.JRadioButton rbo6;
    private javax.swing.JRadioButton rboBolas;
    private javax.swing.JRadioButton rboBolsas;
    private javax.swing.JRadioButton rboBones;
    private javax.swing.JRadioButton rboCabacetes;
    private javax.swing.JRadioButton rboCalcas;
    private javax.swing.JRadioButton rboCamisetas;
    private javax.swing.JRadioButton rboGG;
    private javax.swing.JRadioButton rboLuvas;
    private javax.swing.JRadioButton rboM;
    private javax.swing.JRadioButton rboMeias;
    private javax.swing.JRadioButton rboPP;
    private javax.swing.JRadioButton rboPesos;
    private javax.swing.JRadioButton rboPranchas;
    private javax.swing.JRadioButton rboRaquetes;
    private javax.swing.JRadioButton rboShorts;
    private javax.swing.JRadioButton rboSungas;
    private javax.swing.JRadioButton rboSutias;
    private javax.swing.JRadioButton rboTenis;
    private javax.swing.JToggleButton tglAdidas;
    private javax.swing.JToggleButton tglGYM;
    private javax.swing.JToggleButton tglNike;
    private javax.swing.JToggleButton tglPuma;
    // End of variables declaration//GEN-END:variables
}
